### PR TITLE
Update vue.mdx

### PR DESCRIPTION
**Pull request by kematzy**
Add `VITE_NHOST_URL` environment variable in example to avoid confusion

### CODE REVIEW

**Comment by elitan** [comment]
We should not use `VITE_NHSOT_URL`. Instead, we should update the quickstart to use the following everywhere instead:

```js
const nhost = new NhostClient({
  subdomain: import.meta.env.VITE_NHOST_SUBDOMAIN
  region: import.meta.env.VITE_NHOST_REGION
})
```

@kematzy can you help us with that?

**Comment by kematzy** [comment]
> We should not use `VITE_NHSOT_URL`. Instead, we should update the quickstart to use the following everywhere instead:
> 
> ```js
> const nhost = new NhostClient({
>   subdomain: import.meta.env.VITE_NHOST_SUBDOMAIN
>   region: import.meta.env.VITE_NHOST_REGION
> })
> ```
> 
> @kematzy can you help us with that?

Yes, I'm happy to help with this over the weekend. 

FYI: I was following the Vue Quickstart docs, and only when I added the above ENV variable could I get my local dev version to work. This is why I added it to the docs.

**Comment by elitan** [comment]
Yes, but that's because the initialization of the Nhost client was incorrect. We should use the code below everywhere to avoid using the `VITE_NHOST_URL`.

```js
const nhost = new NhostClient({
  subdomain: import.meta.env.VITE_NHOST_SUBDOMAIN
  region: import.meta.env.VITE_NHOST_REGION
})
```

**Comment by kematzy** [comment]
Please see:
- [nhost/vue-quickstart pull request #1](https://github.com/nhost/vue-quickstart/pull/1)
- [https://github.com/nhost/nhost/pull/1372](https://github.com/nhost/nhost/pull/1372)

I hope these changes are acceptable.

**Comment by elitan** [comment]
Perfect, will check those PRs. Closing this for now.

**Pull request closed without merging**
