### PR TITLE
feat(examples): basic React Native Expo example

### LINKED ISSUE #1607: React Native Expo for ios/web fails with 'Module parse failed' when using @nhost/nhost-js 1.13.2
Here's a repo to reproduce the error:

https://github.com/beepsoft/nhost-js-expo-web-problem2

When using the `@nhost/nhost-js` (1.13.2) in vanilla React Native Expo 46 or above for web  starting the app fails with an error like this in the web console:

```
wrapNativeSuper.js:31 Uncaught Error: Module parse failed: Unexpected token (285:143)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
| }
> const G = typeof window < "u", K = /* @__PURE__ */ new Map(), Pe = (s) => G && typeof localStorage < "u" ? localStorage.getItem(s) : K.get(s) ?? null, Ce = (s, e) => {
|   G && typeof localStorage < "u" ? e ? localStorage.setItem(s, e) : localStorage.removeItem(s) : e ? K.set(s, e) : K.has(s) && K.delete(s);
| }, Ne = (s, e) => {
    at ./node_modules/@nhost/hasura-auth-js/dist/index.esm.js (wrapNativeSuper.js:31:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module.<anonymous> (index.esm.js:1:1)
    at ./node_modules/@nhost/nhost-js/dist/index.esm.js (index.esm.js:250:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (App.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
./node_modules/@nhost/hasura-auth-js/dist/index.esm.js	@	wrapNativeSuper.js:31
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
(anonymous)	@	index.esm.js:1
./node_modules/@nhost/nhost-js/dist/index.esm.js	@	index.esm.js:250
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
./App.tsx	@	App.tsx:1
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
./node_modules/expo/AppEntry.js	@	AppEntry.js:1
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
1	@	log.js:59
__webpack_require__	@	bootstrap:789
(anonymous)	@	bootstrap:856
(anonymous)	@	bootstrap:856
```

To reproduce the error:

```
1. yarn
2. yarn web
```

App startup fails with the error above displayed in the browser's console.

It also fails with `yarn ios`, so nhost is pretty much not usable in Expo at all.

When using 

```
    "expo": "45.0.8",
```

it works, starting from expo 46 it does not. 

This error looks similar to this older one, which has been fixed and worked so far: https://github.com/nhost/nhost/issues/275

### PR DESCRIPTION
**Pull request by szilarddoro**
A super basic example of React Native using Expo.

Fixes #1607

Note:
Unfortunately, a lot of additional dependencies are required for the RN Expo project to work in a PNPM monorepo. Most of these are not required when the project is running in a non-monorepo setup.

### CODE REVIEW

**Comment by beepsoft** [comment]
@szilarddoro I'm not sure how this should be run.  Using `pnpm start`? It doesn't seem to work for me, all kinds of strange errors for iOS and web as well.

**Comment by beepsoft** [comment]
By the way, Expo 48 is just out: https://blog.expo.dev/expo-sdk-48-ccb8302e231

And support for pnpm is just around the corner: https://twitter.com/robjhogan/status/1628460899714449416

**Comment by szilarddoro** [comment]
The Expo CLI still used Expo 47 when I initialized the project 🤔 I'll check if that's still the case.

It's running perfectly fine for me by running:

```
pnpm clean:all && pnpm i && pnpm build && cd examples/react-native-expo && pnpm ios
```

The first two steps should be optional though.

**Comment by szilarddoro** [comment]
Even though this example works as is, it's too much of a hassle to start it, because of the lack of PNPM support for RN + Expo. This is the reason why I'm closing this PR. We'll come back to this once we have proper support (hopefully very soon).

For the nullish coalescing issue that was mentioned earlier, please use the [Webpack configuration](https://github.com/nhost/nhost/issues/1607#issuecomment-1429924002) as a temporary workaround.

**Pull request closed without merging**
