### PR TITLE
fix: update useChangePassword hook interface

### LINKED ISSUE #2204: isLoading does not exist on type 'ChangePasswordHookResult'
**Describe the bug**
TS complains when destructing isLoading from useChangePassword hook
 ```const { changePassword, isLoading, error } = useChangePassword();```
 
However the property is available and updates correctly

I think extending ActionLoadingState for ChangePasswordRHookResult should fix the issue

### PR DESCRIPTION
**Pull request by MainaMary**
fix #2204

### CODE REVIEW

**Comment by onehassan** [comment]
@MainaMary Thank you for submitting this PR 👍  - I'll add a changeset and then merge it

**Comment by onehassan** [comment]
You can also add the changeset yourself if you prefer. Just run pnpm changeset at the root of the project and follow the steps.

**Comment by MainaMary** [comment]
Hey @onehassan I have allowed edit by maintainers

**Comment by onehassan** [comment]
@MainaMary for some reason it still shows a permissions error when I try to push. I'll create another a PR and make sure to include this fix. Otherwise, if you can commit the changeset on your PR, that would be a good option too.

**Comment by onehassan** [comment]
@MainaMary thank you 🙌 
Also don't hesitate to ask me anything related to the changeset, happy to help!

**Comment by MainaMary** [comment]
@onehassan 
I have added the changeset.
Thank you.

**Comment by onehassan** [comment]
@MainaMary Good job and Thank you 🚀

**Review by onehassan — APPROVED** [review]
LGTM

**Pull request merged**
