### PR TITLE
feat (dashboard): Dashboard Deployment

### PR DESCRIPTION
**Pull request by szilarddoro**

### CODE REVIEW

**Comment by plmercereau** [comment]
Internal dependencies in examples should be `"*"` so each example can be copy-pasted outside of the monorepo.
It would have been a problem if we would have published example packages, but we aren't.

**Comment by szilarddoro** [comment]
> Internal dependencies in examples should be `"*"` so each example can be copy-pasted outside of the monorepo.
> It would have been a problem if we would have published example packages, but we aren't.

I'm just testing things here.

**Comment by szilarddoro** [comment]
How likely is this "people copying an example outside of the monorepo" scenario btw? I always found that a strange reasoning TBH.

**Comment by plmercereau** [comment]
Users that would want to use an example as a boilerplate.
Also our examples won't work in codesandbox/stackblitz

**Review by elitan — APPROVED** [review]

**Pull request merged**
