### PR TITLE
useFileUpload.ts added in Vue/src

### PR DESCRIPTION
**Pull request by asdsyd**
Please review the code and suggest if any changes. I new to open source. Your help will be appreciated. Thank you.

### CODE REVIEW

**Comment by asdsyd** [comment]
@plmercereau here is my PR for issue #973

**Comment by plmercereau** [comment]
Hello @asdsyd, thanks for your PR.
However what you did is not a Vue composable, and won't implement file upload.
I suggest you could have a look at the following links first:
- what is a [Vue composable](https://vuejs.org/guide/reusability/composables.html)
- how others composables are implemented in our Vue sdk, for instance [useChangeEmail](https://github.com/nhost/nhost/blob/main/packages/vue/src/useChangeEmail.ts)
- [how file upload React hooks are implemented in our React sdk](https://github.com/nhost/nhost/blob/main/packages/react/src/useFileUpload.ts)

**Comment by asdsyd** [comment]
`import { ? } from 'vue'

import {
    //Are the below imports correct for fileupload in vue?
    createFileUploadMachine,
    FileItemRef,
    FileUploadMachine,
    FileUploadState,
    StorageUploadFileParams,
    UploadFileHandlerResult,
    uploadFilePromise
} from '@nhost/hasura-storage-js'
import { useInterpret, useSelector } from '@xstate/react'

import { useNhostClient } from './useNhostClient'`

Can you review this @plmercereau 
What should be in ? ..which fileupload lib to import for vue. Thanks.

**Comment by asdsyd** [comment]
I am planning to code it step by step with the help of your code reviews and mentoring. Thank you. Please bear with me 😬

**Comment by elitan** [comment]
I'm closing this for now, @asdsyd. Let me know here when you'll start working on it again with the right support around you an we can re-open the PR.

**Pull request closed without merging**
