### PR TITLE
Chore/stripe graphql api masked errors

### PR DESCRIPTION
**Pull request by chandhuDev**
As @elitan pointed me to the issue of #1218 , I have enabled the maskederrors : false such that it can produce the underlying message whenever we are creating the server. Provide me feedback if it is not merged with the main branch as it is my first PR. Thank you

### CODE REVIEW

**Comment by elitan** [comment]
Hey @chandhuDev. Thanks for the PR. However, the parameter `maskedErrors` should not be hard coded to `false`. It should be a parameter just like e.g. `graphiql`.

**Review by elitan — CHANGES_REQUESTED** [review]
Hey @chandhuDev. Thanks for the PR. However, the parameter maskedErrors should not be hard coded to false. It should be a parameter just like e.g. graphiql.

**Comment by szilarddoro** [comment]
Hey @chandhuDev! I'll close this PR because of inactivity. Feel free to create a new one anytime.

**Comment by chandhuDev** [comment]
@szilarddoro okk ! not a problem . I am just busy with my own work at my intern . Sorry not able to commit the update

**Pull request closed without merging**
