### PR TITLE
chore: remove deprecated methods

### PR DESCRIPTION
**Pull request by plmercereau**

### CODE REVIEW

**Review by szilarddoro — COMMENTED** [review]
I know that's going to be a breaking change, but instead of just hiding the from the documentation, we should remove them entirely. I'm afraid that we'd just push this thing in front of us indefinitely if we don't create some kind of action plan for this.

**Comment by plmercereau** [comment]
> I know that's going to be a breaking change, but instead of just hiding the from the documentation, we should remove them entirely. I'm afraid that we'd just push this thing in front of us indefinitely if we don't create some kind of action plan for this.

I'm fine with the suggestion. @elitan ?

**Review by elitan — APPROVED** [review]

**Comment by plmercereau** [comment]
I then removed everything that was deprecated (all of which was deprecated since more than 6 months).
I think this is a major bump too, wdyt?

**Review by szilarddoro — APPROVED** [review]
yes-i-like-a42bb6

**Pull request merged**
