### PR TITLE
fix: back to previous limit

### PR DESCRIPTION
**Pull request by tawsbob**
A Quick fix to improve the user experience at users page which the limit is currently one and make worse to manage the user

### CODE REVIEW

**Comment by dbarrosop** [comment]
Would you mind adding a changeset? You have the instructions [here](https://github.com/nhost/nhost/blob/main/DEVELOPERS.md#changesets). If you are unable we can add it ourselves but it will certainly expedite things if you can do it yourself.

**Review by tawsbob — COMMENTED** [review]
thanks!

**Review by tawsbob — COMMENTED** [review]
@dbarrosop and @onehassan do we need to change the pkg version?

**Comment by onehassan** [comment]
@tawsbob once this PR is merged, the version will be bumped automatically and we will have a new release

**Pull request merged**
