### PR TITLE
fix(hasura-auth-js): resolve social sign-in issue in React Native

### PR DESCRIPTION
**Pull request by onehassan**
fix https://github.com/nhost/nhost/issues/2216

### CODE REVIEW

**Review by dbarrosop — APPROVED** [review]

**Comment by dbarrosop** [comment]
I think a better changelog would be "improve environment/browser detect to include react-native"

**Comment by onehassan** [comment]
> improve environment/browser detect to include react-native

Thanks will apply

**Comment by hadnet** [comment]
So now oauth is now working using React Native?

**Comment by dbarrosop** [comment]
it will when we release this fix. We are finishing up an example/documentation as we speak so stay tuned :)

**Comment by hadnet** [comment]
> it will when we release this fix. We are finishing up an example/documentation as we speak so stay tuned :)

Any updates on this?

**Pull request merged**
